# This is a basic workflow to help you get started with Actions

name: Jfrog_Build
# Bruh
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      build:
        type: choice
        required: true 
        default: 'Last'
        description: Number of build
        options:
        - 'Last'
        - 'PreLast'
        - 'PrePreLast'
        
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
  
    env:
      JF_URL: http://10.202.15.58:8082
      JF_ACCESS_TOKEN: ${{secrets.JFROG_PASSWORD}}
      
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - if: ${{github.event_name}} == 'pull_request' || 'push'
        run: echo "BUILD=Last" >> $env:GITHUB_ENV
      #Setting up jfrog and adding server
      - name: Setup Jfrog
        uses: jfrog/setup-jfrog-cli@v3
        env:
          JF_ACCESS_TOKEN: ${{secrets.JFROG_PASSWORD}}
          BUILD: ''
      - run: |
          jf c add --url=http://10.202.15.58:8082 --user="github" --password="${{secrets.JFROG_PASSWORD}}" --interactive=false --insecure-tls=true
   
      - if: (github.event.inputs.build == 'Last')
        run: echo ("BUILD=" + ((jf rt s "generic-local/jfrog_test/Build/" | ConvertFrom-Json).path.TrimEnd(".txt") -replace '[a-zA-Z-/_]'| Sort-Object -Descending)[0]) >> $env:GITHUB_ENV
      - if: (github.event.inputs.build == 'PreLast')
        run: echo ("BUILD=" + ((jf rt s "generic-local/jfrog_test/Build/" | ConvertFrom-Json).path.TrimEnd(".txt") -replace '[a-zA-Z-/_]'| Sort-Object -Descending)[1]) >> $env:GITHUB_ENV
      - if: (github.event.inputs.build == 'PrePreLast')
        run: echo ("BUILD=" + ((jf rt s "generic-local/jfrog_test/Build/" | ConvertFrom-Json).path.TrimEnd(".txt") -replace '[a-zA-Z-/_]'| Sort-Object -Descending)[2]) >> $env:GITHUB_ENV

      - name: Push build to Artifactory
   
        run: |
          jf rt u "index.html" generic-local/jfrog_test/Build/Build-${{env.BUILD}}.txt
          
          jf rt build-publish latest 1
